# Change these first
owner: earthworksinc # Your GitHub organization or username, where this repository lives
repo: oniyx # The name of this repository

sites:
  - name: Oniyx
    url: https://oniyx.io
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: https://earthworksinc.github.io/oniyx/
  baseUrl: /oniyx
 #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
   # - title: Status
    #  href: /
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
  theme: light
  #themeUrl: https://example.com/custom.css
  css: "

  section.svelte-8lnl4f {
      display: none !important;
    }

    footer.svelte-jbr799 {
      display: none !important;
    }

    header.svelte-ngkazm {
      display: none !important;
    }

    body {
      opacity: 1;
    }
  
  #body {
   #   opacity: 0.7;
   # }

    #footer.svelte-jbr799 {
    #  display: none !important;
    #}

    #header.svelte-ngkazm {
    #  display: none !important;
    #}
  "

  #js: |
  #  window.onload = function () {
  #    // Remove the footer
  #    var footer = document.querySelector('footer.svelte-jbr799');
  #    if (footer) footer.remove();

   #   // Remove the "All systems are operational" article
   #   var statusArticle = document.querySelector('article.up');
   #   if (statusArticle) statusArticle.remove();
   # };
  # customFootHtml: '<footer style="text-align: center; padding: 1em; color: #ccc;">© 2025 Earthworks Inc. | All rights reserved.</footer>'
  #js: "window.onload = function () { var main = document.querySelector('main'); if (main) main.style.display = 'none'; var footer = document.querySelector('footer'); if (footer) footer.remove(); var article = document.querySelector('article.up'); if (article) article.remove(); };"

